version: '3.4'

services:
    easynetq.rabbitmq.api:
        image: ${DOCKER_REGISTRY-}easynetqrabbitmqapi
        build:
            context: .
            dockerfile: EasyNetQ.RabbitMQ.Api/Dockerfile

    rabbitmq:
            image: rabbitmq:3-management-alpine
            container_name: rabbitmq
            ports:
                - 5672:5672
                - 15672:15672
            volumes:
                - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
                - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
            environment:
                - RABBITMQ_DEFAULT_USER=messaging
                - RABBITMQ_DEFAULT_PASS=containers
            networks:
                - rabbitmq_go_net

networks:
    rabbitmq_go_net:
        driver: bridge